FROM node:20.12.0-alpine3.19

WORKDIR /app

COPY package.json turbo.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install

# Filter the build down to just one app (replace 'your-app-name' with the actual app name)
RUN npm run build

CMD ["npm", "run", "start-web-app"]
