name: Build success

on:
    pull_request:
        branches:
            - main

jobs:
    lint:
        name: Run Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20'
            
            - name: Install dependencies for linting
              run: npm install

            - name: Run lint command
              run: npm run lint

    build:
        name: Build repo
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20'
            
            - name: Install dependencies
              run: npm install

            - name: Run build command
              run: npm run build
            

